version: '3.4'
services:
  app:
    build:
      context: .
      target: development
    image: react/react-seed-nodejs-12.13.1-alpine3.10
    working_dir: /app
    command: yarn start
    ports:
      - 8082:3000
    networks:
      - web
    volumes:
      - ./:/app

networks:
  web:
    external:
      name: react-seed_webgateway